import { Component } from '@angular/core';

import { HeaderComponent } from '../components/header/header.component';

@Component({
  standalone: true,
  imports: [HeaderComponent],
  template: `
    <div class="page-container">
      <app-header></app-header>
      <div class="about-content">
        <h1>About</h1>
        <p>
          Austen is an open source web app that helps you discover and share the relationships
          between characters in novels. It shows a visual map of how characters
          are connected, using Mermaid syntax generated by Google Gemini. You
          can also share the generated graphs with your friends.
        </p>
        <h2>Stacks</h2>
        <ul>
          <li>Angular</li>
          <li>Analog</li>
          <li>RxJS</li>
          <li>Supabase</li>
          <li>Mermaid</li>
          <li>TypeScript</li>
          <li>Google Generative AI</li>
        </ul>
      </div>
    </div>
  `,
})
export default class AboutPageComponent {}
